// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "../Sobre.hpp"
#include "../Paquete.hpp"
// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[Verificando el costo del Sobre sin costo extra]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Envio* s1;
    s1=new Sobre(rem, des, 5.5, 10.0);
    SECTION("Verificando el cálculo del costo del sobre sin costo extra")  
    {
        REQUIRE(s1->calculaCosto() == 150.50);
    }
}

// =====================
// tests for exercise 2
// ---------------------

TEST_CASE("Ex2", "[Verificando el costo del Sobre con costo extra]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Envio* s1;
    s1=new Sobre(rem, des, 25.5, 30.0);
    SECTION("Verificando el cálculo del costo del sobre con costo extra")  
    {
        REQUIRE(s1->calculaCosto() == 230.40);
    }
}

TEST_CASE("Ex3", "[Verificando el costo del Paquete]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Envio* paq1;
    paq1=new Paquete(rem, des, 5, 10, 15, 20);
    SECTION("Verificando el cálculo del costo del paquete")  
    {
        REQUIRE(paq1->calculaCosto() == 267.75);
    }
}

